services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    volumes:
      - .:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  browser-sync:
    build:
      context: .
      dockerfile: Dockerfile.bs
    ports:
      - "3000:3000"
    depends_on:
      - caddy
    volumes:
      - .:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
